/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roboticscontrol;

/**
 *
 * @author braden
 */
public class UserInterface extends javax.swing.JFrame implements Runnable {
    /**
     * Creates new form UserInterface
     */
	
	MessageService messageService;
	private boolean running;
	
    public UserInterface(MessageService ms) {
		this.running = true;
        initComponents();
		this.messageService = ms;
		this.setVisible(true);
    }
	
	public void run() {
		System.out.println("Interface is running.");
		while (running) {
			String message = messageService.receiveFromRobot();
			if (message != null) {
				System.out.println("UI: Received a message: " + message);
				parseMessage(message);
			}
		}
	}
	
	private void parseMessage(String m) {
		String[] message = m.split(":");
		String command = message[0];
		int parameter = Integer.parseInt(message[1]);
		switch(command) {
			case "updateTemp":			updateTemp(parameter);
										break;
//			case "updateSpeed":			updateSpeed(parameter);
//										break;
//			case "updateClawStatus":	updateClawStatus(parameter);
//										break;
//			case "updateX":				updateX(parameter);
//										break;
//			case "updateY":				updateY(parameter);
//										break;
			default:					break;
		}
		

		
	}
	
	private void updateTemp(int t) {
		temperatureLabel.setText(Integer.toString(t));
	}
	
	

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actuatorControlsPanel = new javax.swing.JPanel();
        clawButton = new javax.swing.JButton();
        armAnglePanel = new javax.swing.JPanel();
        movementControlsPanel = new javax.swing.JPanel();
        turnLeftButton = new javax.swing.JButton();
        turnRightButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        speedPanel = new javax.swing.JPanel();
        decSpeedButton = new javax.swing.JButton();
        incSpeedButton = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        gpsDisplayPanel = new javax.swing.JPanel();
        sensorControlsPanel = new javax.swing.JPanel();
        cameraButton = new javax.swing.JButton();
        thermoButton = new javax.swing.JButton();
        temperatureLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actuatorControlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Actuator Controls"));

        clawButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roboticscontrol/Claw-Open.png"))); // NOI18N
        clawButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clawButtonMousePressed(evt);
            }
        });

        armAnglePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout armAnglePanelLayout = new javax.swing.GroupLayout(armAnglePanel);
        armAnglePanel.setLayout(armAnglePanelLayout);
        armAnglePanelLayout.setHorizontalGroup(
            armAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        armAnglePanelLayout.setVerticalGroup(
            armAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout actuatorControlsPanelLayout = new javax.swing.GroupLayout(actuatorControlsPanel);
        actuatorControlsPanel.setLayout(actuatorControlsPanelLayout);
        actuatorControlsPanelLayout.setHorizontalGroup(
            actuatorControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actuatorControlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(armAnglePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(actuatorControlsPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(clawButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actuatorControlsPanelLayout.setVerticalGroup(
            actuatorControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actuatorControlsPanelLayout.createSequentialGroup()
                .addComponent(armAnglePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clawButton)
                .addContainerGap())
        );

        movementControlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Movement Controls"));

        turnLeftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roboticscontrol/ArrowLeft.png"))); // NOI18N
        turnLeftButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                turnLeftButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                turnLeftButtonMouseReleased(evt);
            }
        });

        turnRightButton.setIcon(new javax.swing.ImageIcon("/Users/braden/Documents/ArrowRight.png")); // NOI18N
        turnRightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                turnRightButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                turnRightButtonMouseReleased(evt);
            }
        });

        stopButton.setBackground(new java.awt.Color(255, 102, 102));
        stopButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        stopButton.setText("STOP");
        stopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stopButtonMousePressed(evt);
            }
        });

        speedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout speedPanelLayout = new javax.swing.GroupLayout(speedPanel);
        speedPanel.setLayout(speedPanelLayout);
        speedPanelLayout.setHorizontalGroup(
            speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        speedPanelLayout.setVerticalGroup(
            speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        decSpeedButton.setText("Decrease Speed");
        decSpeedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                decSpeedButtonMousePressed(evt);
            }
        });

        incSpeedButton.setText("Increase Speed");
        incSpeedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                incSpeedButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout movementControlsPanelLayout = new javax.swing.GroupLayout(movementControlsPanel);
        movementControlsPanel.setLayout(movementControlsPanelLayout);
        movementControlsPanelLayout.setHorizontalGroup(
            movementControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movementControlsPanelLayout.createSequentialGroup()
                .addGroup(movementControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movementControlsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(turnLeftButton)
                        .addGap(18, 18, 18)
                        .addComponent(turnRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(movementControlsPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(movementControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(speedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(decSpeedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(incSpeedButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        movementControlsPanelLayout.setVerticalGroup(
            movementControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movementControlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movementControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turnLeftButton)
                    .addComponent(turnRightButton))
                .addGap(23, 23, 23)
                .addComponent(incSpeedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decSpeedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(stopButton)
                .addContainerGap())
        );

        gpsDisplayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("GPS Display"));

        javax.swing.GroupLayout gpsDisplayPanelLayout = new javax.swing.GroupLayout(gpsDisplayPanel);
        gpsDisplayPanel.setLayout(gpsDisplayPanelLayout);
        gpsDisplayPanelLayout.setHorizontalGroup(
            gpsDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        gpsDisplayPanelLayout.setVerticalGroup(
            gpsDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gpsDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gpsDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sensorControlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor Controls"));

        cameraButton.setText("Camera");
        cameraButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButtonMousePressed(evt);
            }
        });

        thermoButton.setText("Thermometer");
        thermoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                thermoButtonMousePressed(evt);
            }
        });

        temperatureLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        temperatureLabel.setText("72 °F");

        javax.swing.GroupLayout sensorControlsPanelLayout = new javax.swing.GroupLayout(sensorControlsPanel);
        sensorControlsPanel.setLayout(sensorControlsPanelLayout);
        sensorControlsPanelLayout.setHorizontalGroup(
            sensorControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sensorControlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sensorControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cameraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sensorControlsPanelLayout.createSequentialGroup()
                        .addComponent(thermoButton)
                        .addGap(17, 17, 17)
                        .addComponent(temperatureLabel)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sensorControlsPanelLayout.setVerticalGroup(
            sensorControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sensorControlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cameraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sensorControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thermoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureLabel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        messageLog.setColumns(20);
        messageLog.setRows(5);
        jScrollPane2.setViewportView(messageLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(movementControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sensorControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(actuatorControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actuatorControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sensorControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(movementControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void turnRightButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turnRightButtonMousePressed
	    	messageService.sendToRobot("turn:1");
    }//GEN-LAST:event_turnRightButtonMousePressed

        private void turnLeftButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turnLeftButtonMousePressed
	    	messageService.sendToRobot("turn:-1");
        }//GEN-LAST:event_turnLeftButtonMousePressed

        private void incSpeedButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incSpeedButtonMousePressed
			messageService.sendToRobot("speed:1");
        }//GEN-LAST:event_incSpeedButtonMousePressed

        private void decSpeedButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decSpeedButtonMousePressed
			messageService.sendToRobot("speed:-1");
        }//GEN-LAST:event_decSpeedButtonMousePressed

        private void stopButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMousePressed
			messageService.sendToRobot("stop:0");
        }//GEN-LAST:event_stopButtonMousePressed

        private void clawButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clawButtonMousePressed
            messageService.sendToRobot("claw:0");
        }//GEN-LAST:event_clawButtonMousePressed

        private void cameraButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButtonMousePressed
            messageService.sendToRobot("camera:0");
        }//GEN-LAST:event_cameraButtonMousePressed

        private void thermoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thermoButtonMousePressed
            messageService.sendToRobot("temp:0");
        }//GEN-LAST:event_thermoButtonMousePressed

    private void turnRightButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turnRightButtonMouseReleased
        messageService.sendToRobot("turn:0");
    }//GEN-LAST:event_turnRightButtonMouseReleased

    private void turnLeftButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turnLeftButtonMouseReleased
        messageService.sendToRobot("turn:0");
    }//GEN-LAST:event_turnLeftButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actuatorControlsPanel;
    private javax.swing.JPanel armAnglePanel;
    private javax.swing.JButton cameraButton;
    private javax.swing.JButton clawButton;
    private javax.swing.JButton decSpeedButton;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel gpsDisplayPanel;
    private javax.swing.JButton incSpeedButton;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea messageLog;
    private javax.swing.JPanel movementControlsPanel;
    private javax.swing.JPanel sensorControlsPanel;
    private javax.swing.JPanel speedPanel;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JButton thermoButton;
    private javax.swing.JButton turnLeftButton;
    private javax.swing.JButton turnRightButton;
    // End of variables declaration//GEN-END:variables
}
